# Generated by Django 4.1 on 2022-08-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SwimPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapotic_id', models.IntegerField(unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('image_url', models.URLField()),
                ('import_id', models.CharField(max_length=20)),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('address', models.CharField(default=None, max_length=200)),
                ('web', models.URLField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('refreshment', models.CharField(choices=[('Restaurant on site', 'Restaurant on site'), ('No restaurant', 'No restaurant')], max_length=50)),
                ('diving', models.CharField(choices=[('Suitable for diving', 'Suitable for diving'), ('Not suitable for diving', 'Not suitable for diving')], max_length=50)),
                ('entrance', models.CharField(choices=[('Entrance fee', 'Entrance fee'), ('No entrance fee', 'No entrance fee')], max_length=20)),
                ('parking', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('nudist_beach', models.CharField(choices=[('Suitable for nudists', 'Suitable for nudists'), ('Not suitable for nudists', 'Not suitable for nudists')], max_length=30)),
                ('video', models.URLField()),
                ('dog_swimming', models.CharField(choices=[('Suitable for dogs', 'Suitable for dogs'), ('Not suitable for dogs', 'Not suitable for dogs')], max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swimplaces.category')),
            ],
        ),
    ]
