# Generated by Django 4.1 on 2022-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0004_alter_swimplace_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='description1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='description2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
