# Generated by Django 4.1 on 2022-08-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0005_alter_swimplace_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
