# Generated by Django 4.1 on 2022-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0006_alter_swimplace_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
