# Generated by Django 4.1 on 2022-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0007_alter_swimplace_e_mail_alter_swimplace_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='dog_swimming',
            field=models.CharField(blank=True, choices=[('Suitable for dogs', 'Suitable for dogs'), ('Not suitable for dogs', 'Not suitable for dogs')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
