# Generated by Django 4.1 on 2022-08-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0008_alter_swimplace_dog_swimming_alter_swimplace_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='parking',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
