# Generated by Django 4.1 on 2022-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0009_alter_swimplace_link_alter_swimplace_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='import_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
