# Generated by Django 4.1 on 2022-08-15 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0020_alter_swimplace_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimplace',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='swimplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swimplaces.swimplace'),
        ),
    ]
