# Generated by Django 4.1 on 2022-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0022_alter_comment_swimplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
