# Generated by Django 4.1 on 2022-08-15 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0023_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='swimplaces.category'),
        ),
    ]
