# Generated by Django 4.1 on 2022-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0024_alter_swimplace_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimplace',
            name='from_cr_center',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
