# Generated by Django 4.1 on 2022-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0026_alter_swimplace_from_cr_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimplace',
            name='from_cr_center',
            field=models.FloatField(blank=True, default=None, editable=False, null=True),
        ),
    ]
