# Generated by Django 4.1 on 2022-08-18 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0027_alter_swimplace_from_cr_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.FloatField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('swimplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='swimplaces.swimplace')),
            ],
        ),
    ]
