# Generated by Django 4.1 on 2022-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0028_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='degree',
            field=models.FloatField(blank=True, default='Not available', null=True),
        ),
    ]
