# Generated by Django 4.1 on 2022-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimplaces', '0030_alter_temperature_swimplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimplace',
            name='mapotic_id',
        ),
        migrations.AlterField(
            model_name='swimplace',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
